addons:
  postgresql: 9.6

language: ruby

node_js:
  - 15.5.1

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.10
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn install
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake

rvm:
  - 2.7.2