version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.7.2-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          DATABASE_URL: postgres://postgres:password@localhost:5432/tech_cast_test
          RAILS_ENV: test
          RAILS_MASTER_KEY: $RAILS_MASTER_KEY

      - image: circleci/postgres:12.0

    working_directory: ~/qi-ps

    steps:
      - checkout
      - run:
          name: "echo an env var that is part of QI-PS test context"
          command: |
            echo $RAILS_MASTER_KEY
      - restore_cache:
          keys:
            - qi-ps-bundle-v1-{{ checksum "Gemfile.lock" }}
            - qi-ps-bundle-v1-
      - run:
          name: install dependencies
          command: |
            sudo apt-get update -qq && sudo apt-get -y install \
              autoconf \
              automake \
              build-essential \
              cmake \
              git-core \
              libass-dev \
              libfreetype6-dev \
              libgnutls28-dev \
              libsdl2-dev \
              libtool \
              libva-dev \
              libvdpau-dev \
              libvorbis-dev \
              libxcb1-dev \
              libxcb-shm0-dev \
              libxcb-xfixes0-dev \
              pkg-config \
              texinfo \
              wget \
              yasm \
              zlib1g-dev

      - run:
          name: install ffmpeg
          command: |
            sudo apt-get install ffmpeg
      - run:
          name: install dependencies
          command: |
            bundle -v
            sudo gem install bundler:2.1.4 --default
            bundle -v
            bundle check || bundle install

      - save_cache:
          key: qi-ps-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: yarn install
      # Wait for DB
      - run: dockerize -wait tcp://0.0.0.0:5432 -timeout 1m
      - run:
          name: Setup DB
          command: |
            bundle exec rails db:create db:schema:load --trace

      # run tests!
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
